version: '2'
services:
    splash:
        image: 'scrapinghub/splash'
        ports:
            - "8050:8050"
    scrapy:
        build: .
        ports:
            - "5000:5000"
        links:
            - splash
